# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: critiq
  host: localhost
  username: critiq
  password: 
test:
  adapter: postgresql
  encoding: unicode
  database: critiq_test
  host: localhost
  pool: 5
  username: critiq
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  pool: 5
  username: critiq
  password: